<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <Description>Managed geometry types for Darp Tesseract bindings.</Description>
    <PackageTags>Darp;Rosslight;Geometry;Linear Algebra;Quaternion;Transform</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
